test_suites:
- name: lint
  job_name: lint
  script_path: /root/okta/okta-ui-configs/scripts
  sort_order: '1'
  timeout: '20'
  script_name: lint
  criteria: MERGE
  queue_name: medium
- name: unit
  job_name: unit
  script_path: /root/okta/okta-ui-configs/scripts
  sort_order: '2'
  timeout: '20'
  script_name: unit
  criteria: MERGE
  queue_name: medium
- name: publish
  job_name: publish
  script_path: /root/okta/okta-ui-configs/scripts
  sort_order: '3'
  timeout: '20'
  script_name: publish
  criteria: MERGE
  queue_name: medium
